[package]
name = "eflect"
version = "0.0.0"
edition = "2018"

[dependencies]
clap = "2.33.3"
ctrlc = "3"
procfs = "0.10.1"
protobuf = "2.25.1"
grpc            = "~0.8"
futures         = "~0.3"

[build-dependencies]
protoc-rust-grpc = "~0.8"
